### ISSUE TITLE
Crashes in release 1.27.0.1

### ISSUE THREAD

**Issue by rabu861** [Catfriend1/syncthing-android#1061]
https://github.com/Catfriend1/syncthing-android/issues/1048

Unfortunately, SyncThing-Fork still crashes in release v1.27.0.1, although less often, but at least once a day ...

[syncthing.log](https://github.com/Catfriend1/syncthing-android/files/13619884/syncthing.log)

**Comment by sjpatel21** [comment]
I am also facing similar issue. Syncthing fork crashes almost everyday. 
Here are my logs 
[Syncthing.log](https://github.com/Catfriend1/syncthing-android/files/13626542/Syncthing.log)

**Comment by blaueente** [comment]
Since update to v1.27.0 or Android 14 December , (not sure, the updates happened in the same day)   syncthing crashes immediately after start. reproducably. 


```
18:01:33E/AndroidRuntime FATAL EXCEPTION: main
18:01:33E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 20690
18:01:33E/AndroidRuntime android.content.ActivityNotFoundException: No Activity found to handle Intent { act=.activities.LogActivity }
18:01:33E/AndroidRuntime 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
18:01:33E/AndroidRuntime 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
18:01:33E/AndroidRuntime 	at android.app.Activity.startActivityForResult(Activity.java:5615)
18:01:33E/AndroidRuntime 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
18:01:33E/AndroidRuntime 	at android.app.Activity.startActivityForResult(Activity.java:5573)
18:01:33E/AndroidRuntime 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
18:01:33E/AndroidRuntime 	at android.app.Activity.startActivity(Activity.java:6071)
18:01:33E/AndroidRuntime 	at android.app.Activity.startActivity(Activity.java:6038)
18:01:33E/AndroidRuntime 	at android.preference.Preference.performClick(Preference.java:1181)
18:01:33E/AndroidRuntime 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:261)
18:01:33E/AndroidRuntime 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
18:01:33E/AndroidRuntime 	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
18:01:33E/AndroidRuntime 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
18:01:33E/AndroidRuntime 	at android.widget.AbsListView$3.run(AbsListView.java:4244)
18:01:33E/AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:958)
18:01:33E/AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
18:01:33E/AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:205)
18:01:33E/AndroidRuntime 	at android.os.Looper.loop(Looper.java:294)
18:01:33E/AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8194)
18:01:33E/AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
18:01:33E/AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
18:01:33E/AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
18:01:47E/AndroidRuntime FATAL EXCEPTION: main
18:01:47E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 21712
18:01:47E/AndroidRuntime android.content.ActivityNotFoundException: No Activity found to handle Intent { act=.activities.LogActivity }
18:01:47E/AndroidRuntime 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
18:01:47E/AndroidRuntime 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
18:01:47E/AndroidRuntime 	at android.app.Activity.startActivityForResult(Activity.java:5615)
18:01:47E/AndroidRuntime 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
18:01:47E/AndroidRuntime 	at android.app.Activity.startActivityForResult(Activity.java:5573)
18:01:47E/AndroidRuntime 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
18:01:47E/AndroidRuntime 	at android.app.Activity.startActivity(Activity.java:6071)
18:01:47E/AndroidRuntime 	at android.app.Activity.startActivity(Activity.java:6038)
18:01:47E/AndroidRuntime 	at android.preference.Preference.performClick(Preference.java:1181)
18:01:47E/AndroidRuntime 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:261)
18:01:47E/AndroidRuntime 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
18:01:47E/AndroidRuntime 	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
18:01:47E/AndroidRuntime 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
18:01:47E/AndroidRuntime 	at android.widget.AbsListView$3.run(AbsListView.java:4244)
18:01:47E/AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:958)
18:01:47E/AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
18:01:47E/AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:205)
18:01:47E/AndroidRuntime 	at android.os.Looper.loop(Looper.java:294)
18:01:47E/AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8194)
18:01:47E/AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
18:01:47E/AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
18:01:47E/AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
18:03:50E/AndroidRuntime FATAL EXCEPTION: main
18:03:50E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 22012
18:03:50E/AndroidRuntime android.content.ActivityNotFoundException: No Activity found to handle Intent { act=.activities.LogActivity }
18:03:50E/AndroidRuntime 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
18:03:50E/AndroidRuntime 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
18:03:50E/AndroidRuntime 	at android.app.Activity.startActivityForResult(Activity.java:5615)
18:03:50E/AndroidRuntime 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
18:03:50E/AndroidRuntime 	at android.app.Activity.startActivityForResult(Activity.java:5573)
18:03:50E/AndroidRuntime 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
18:03:50E/AndroidRuntime 	at android.app.Activity.startActivity(Activity.java:6071)
18:03:50E/AndroidRuntime 	at android.app.Activity.startActivity(Activity.java:6038)
18:03:50E/AndroidRuntime 	at android.preference.Preference.performClick(Preference.java:1181)
18:03:50E/AndroidRuntime 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:261)
18:03:50E/AndroidRuntime 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
18:03:50E/AndroidRuntime 	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
18:03:50E/AndroidRuntime 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
18:03:50E/AndroidRuntime 	at android.widget.AbsListView$3.run(AbsListView.java:4244)
18:03:50E/AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:958)
18:03:50E/AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
18:03:50E/AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:205)
18:03:50E/AndroidRuntime 	at android.os.Looper.loop(Looper.java:294)
18:03:50E/AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8194)
18:03:50E/AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
18:03:50E/AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
18:03:50E/AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
19:01:16I/Util     runShellCommandGetOutput: Exited with code 0
19:01:20W/androidtc TextClassifier called on main thread
19:01:20W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@def50dc
19:01:21W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@ae1d0e
19:01:21W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@252df74
19:01:21W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@f787ee0
19:01:30W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@34ab479
19:01:30W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@6979b1
19:01:30W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@8eaffed
19:01:30W/androidtc TextClassifier called on main thread
19:01:30W/androidtc TextClassifier called on main thread
19:01:32W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@295cb2a
19:01:34W/androidtc TextClassifier called on main thread
19:01:34W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@34e6292
19:01:35W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@fd61416
19:01:35W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@4338fee
19:01:35W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@5ccbcfa
19:01:35W/androidtc TextClassifier called on main thread
19:01:35W/androidtc TextClassifier called on main thread
19:01:36I/Util     runShellCommandGetOutput: Exited with code 0
19:01:36W/WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@38d1fe4```

**Comment by stuart12** [comment]
Syncthing-Fork Wrapper Version v1.27.0.1 fails to start Syncthing. When I try to force a start, the orange target goes green for a few seconds and then turns back orange. Syncthing-Fork shows a notification **Syncthing has crashed (exit code 2)**. Is this a bug in Syncthing-Fork or in Syncthing itself?
```
12-12 22:02:27.303 11227     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
12-12 22:02:27.304 11227     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xbe56d476a000]
12-12 22:02:27.304 11227     0 E Go      : 
12-12 22:02:27.304 11227     0 E Go      : goroutine 482 [running]:
12-12 22:02:27.304 10228 11229 W SyncthingNativeCode: panic: runtime error: invalid memory address or nil pointer dereference
12-12 22:02:27.304 10228 11229 W SyncthingNativeCode: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xbe56d476a000]
12-12 22:02:27.305 10228 11229 W SyncthingNativeCode: 
12-12 22:02:27.305 10228 11229 W SyncthingNativeCode: goroutine 482 [running]:
12-12 22:02:27.308 10228 11229 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).startLocked(_, {{0x4000367a00, 0xb}, {0x4000367a18, 0x5}, 0x0, {0x40003bec30, 0x23}, 0x0, {0x40003c6000, ...}, ...}, ...)
12-12 22:02:27.308 11227     0 E Go      : github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).startLocked(_, {{0x4000367a00, 0xb}, {0x4000367a18, 0x5}, 0x0, {0x40003bec30, 0x23}, 0x0, {0x40003c6000, ...}, ...}, ...)
12-12 22:02:27.309 10228 11229 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/model/indexhandler.go:419 +0x100
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/model/indexhandler.go:419 +0x100
12-12 22:02:27.309 11227     0 E Go      : github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).AddIndexInfo(0x400035b450, {0x4002cec2f0, 0xb}, 0x4000e8e8c0)
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/model/indexhandler.go:439 +0x414
12-12 22:02:27.309 11227     0 E Go      : github.com/syncthing/syncthing/lib/model.(*model).ccHandleFolders(_, {_, _, _}, {{0x5d, 0x7a, 0x30, 0xf, 0x3d, 0x59, ...}, ...}, ...)
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/model/model.go:1499 +0x5a4
12-12 22:02:27.309 11227     0 E Go      : github.com/syncthing/syncthing/lib/model.(*model).ClusterConfig(0x400019a180, {0xbe56d4a418f8, 0x4000d9a9b0}, {{0x40002d7200?, 0x4000182088?, 0x4000182088?}, 0x68?})
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/model/model.go:1296 +0x740
12-12 22:02:27.309 11227     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*connectionWrappingModel).ClusterConfig(0x4000694d68?, {{0x40002d7200?, 0x10?, 0xbe56d487d7c0?}, 0x1?})
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:1143 +0x50
12-12 22:02:27.309 11227     0 E Go      : github.com/syncthing/syncthing/lib/protocol.encryptedModel.ClusterConfig(...)
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/encryption.go:155
12-12 22:02:27.309 11227     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*rawConnection).dispatcherLoop(0x4000b6e900)
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:496 +0x2fc
12-12 22:02:27.309 11227     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func2()
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:307 +0x24
12-12 22:02:27.309 11227     0 E Go      : created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start in goroutine 97
12-12 22:02:27.309 11227     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:306 +0x144
```

**Comment by stuart12** [comment]
Syncthing-Fork Wrapper Version v1.26.1.0 cannot start Syncthing either:
```
12-12 22:44:18.125 13519 14428 I SyncthingNativeCode: [THOPU] INFO: Completed initial scan of sendreceive folder "AndroidMovies" (5ng3z-setts)
12-12 22:44:19.056 14427     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
12-12 22:44:19.056 14427     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xb411031eaaf0]
12-12 22:44:19.056 14427     0 E Go      : 
12-12 22:44:19.056 14427     0 E Go      : goroutine 300 [running]:
12-12 22:44:19.057 14427     0 E Go      : github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).startLocked(_, {{0x40003dda80, 0xb}, {0x40003dda98, 0x5}, 0x0, {0x4000430540, 0x23}, 0x0, {0x400027e000, ...}, ...}, ...)
12-12 22:44:19.057 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/model/indexhandler.go:419 +0x100
12-12 22:44:19.057 14427     0 E Go      : github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).AddIndexInfo(0x4002e785f0, {0x4002e13080, 0xb}, 0x40028cfa40)
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: panic: runtime error: invalid memory address or nil pointer dereference
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xb411031eaaf0]
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: 
12-12 22:44:19.057 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/model/indexhandler.go:439 +0x414
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: goroutine 300 [running]:
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).startLocked(_, {{0x40003dda80, 0xb}, {0x40003dda98, 0x5}, 0x0, {0x4000430540, 0x23}, 0x0, {0x400027e000, ...}, ...}, ...)
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/model/indexhandler.go:419 +0x100
12-12 22:44:19.057 14427     0 E Go      : github.com/syncthing/syncthing/lib/model.(*model).ccHandleFolders(_, {_, _, _}, {{0x5d, 0x7a, 0x30, 0xf, 0x3d, 0x59, ...}, ...}, ...)
12-12 22:44:19.057 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/model/model.go:1496 +0x5a4
12-12 22:44:19.057 14427     0 E Go      : github.com/syncthing/syncthing/lib/model.(*model).ClusterConfig(0x400019c180, {0xb411034c9b98, 0x40012ae300}, {{0x4002baa600?, 0x4000182088?, 0x4000182088?}, 0x68?})
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/model.(*indexHandlerRegistry).AddIndexInfo(0x4002e785f0, {0x4002e13080, 0xb}, 0x40028cfa40)
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/model/indexhandler.go:439 +0x414
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/model.(*model).ccHandleFolders(_, {_, _, _}, {{0x5d, 0x7a, 0x30, 0xf, 0x3d, 0x59, ...}, ...}, ...)
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/model/model.go:1496 +0x5a4
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/model.(*model).ClusterConfig(0x400019c180, {0xb411034c9b98, 0x40012ae300}, {{0x4002baa600?, 0x4000182088?, 0x4000182088?}, 0x68?})
12-12 22:44:19.057 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/model/model.go:1296 +0x740
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/model/model.go:1296 +0x740
12-12 22:44:19.057 14427     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*connectionWrappingModel).ClusterConfig(0x4003adcd68?, {{0x4002baa600?, 0x10?, 0xb411032ff7c0?}, 0x1?})
12-12 22:44:19.057 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/protocol.(*connectionWrappingModel).ClusterConfig(0x4003adcd68?, {{0x4002baa600?, 0x10?, 0xb411032ff7c0?}, 0x1?})
12-12 22:44:19.058 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:1143 +0x50
12-12 22:44:19.058 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/protocol/protocol.go:1143 +0x50
12-12 22:44:19.058 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/protocol.encryptedModel.ClusterConfig(...)
12-12 22:44:19.058 14427     0 E Go      : github.com/syncthing/syncthing/lib/protocol.encryptedModel.ClusterConfig(...)
12-12 22:44:19.058 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/protocol/encryption.go:155
12-12 22:44:19.058 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/encryption.go:155
12-12 22:44:19.059 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/protocol.(*rawConnection).dispatcherLoop(0x400089a900)
12-12 22:44:19.059 14427     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*rawConnection).dispatcherLoop(0x400089a900)
12-12 22:44:19.059 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/protocol/protocol.go:496 +0x2fc
12-12 22:44:19.059 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:496 +0x2fc
12-12 22:44:19.059 13519 14429 W SyncthingNativeCode: github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func2()
12-12 22:44:19.059 14427     0 E Go      : github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func2()
12-12 22:44:19.059 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/protocol/protocol.go:307 +0x24
12-12 22:44:19.059 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:307 +0x24
12-12 22:44:19.060 13519 14429 W SyncthingNativeCode: created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start in goroutine 83
12-12 22:44:19.060 14427     0 E Go      : created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start in goroutine 83
12-12 22:44:19.060 13519 14429 W SyncthingNativeCode: 	github.com/syncthing/syncthing/lib/protocol/protocol.go:306 +0x144
12-12 22:44:19.060 14427     0 E Go      : 	github.com/syncthing/syncthing/lib/protocol/protocol.go:306 +0x144

```

**Comment by stuart12** [comment]
the problem is more subtle. I can start Syncthing with the telephone in airplane mode. It then keeps running when I turn airplane mode off.

**Comment by RaggedStaff** [comment]
> the problem is more subtle. I can start Syncthing with the telephone in airplane mode. It then keeps running when I turn airplane mode off.

This worlaround seems to be working for me. 😕

**Comment by Boebbele** [comment]
Yes it crashed on every start.

**Comment by ChronosXYZ** [comment]
I have crashes too. Cannot start Syncthing at all.
OS: Android 14
Phone: Google Pixel 6
Logs: [syncthing.txt](https://github.com/Catfriend1/syncthing-android/files/13676418/syncthing.txt)

**Comment by Catfriend1** [comment]
We will release the GitHub APK shortly (v1.27.2.0). Please upgrade to that.

**Comment by Catfriend1** [comment]
New release: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.27.2.0
