### ISSUE TITLE
install failure on Android14 (build UQ1A.240105.002)

### ISSUE THREAD

**Issue by jolz** [Catfriend1/syncthing-android#1075]
### Description of the issue
install via f-droid store failes (without error message). 

i assume the same bug as https://github.com/uazo/cromite/issues/595 (something about resizing "themed app icon")

### Reproduction Steps
uninstall syncthing-fork, then re-install.
i assume than normal "update"  produces the same issue. (update did not work for me, so I uninstalled syncthing-fork. re-installation failed.)

### Version Information
- App Version: 1.27.2.1, 1.27.0.1, .126.1.0
- Syncthing Version: ---
- Android Version: Android 14 (build number UQ1A.240105.002 ) 
- Device manufacturer: Google 
- Device model: Pixel 6

### Device platform info

```sh
[ro.product.build.date]: [Tue Nov 21 18:20:17 UTC 2023]
[ro.product.build.date.utc]: [1700590817]
[ro.product.build.fingerprint]: [google/oriole/oriole:14/UQ1A.240105.002/11129216:user/release-keys]
[ro.product.build.id]: [UQ1A.240105.002]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [11129216]
[ro.product.build.version.release]: [14]
[ro.product.build.version.release_or_codename]: [14]
[ro.product.build.version.sdk]: [34]

```

### Android Log

```sh
01-16 09:21:33.111  1017  2552 I WifiHAL : Creating message to get link statistics; iface = 47
01-16 09:21:33.234  1017  2552 I WifiHAL : In GetLinkStatsCommand::handleResponse
01-16 09:21:33.236  1017  2552 E IPCThreadState: binder thread pool (1 threads) starved for 126 ms
01-16 09:21:33.419   618   684 I hwc-display: [PrimaryDisplay] setActiveConfigWithConstraints: config(37)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: FATAL EXCEPTION: main
01-16 09:21:33.533  8077  8077 E AndroidRuntime: Process: com.google.android.packageinstaller, PID: 8077
01-16 09:21:33.533  8077  8077 E AndroidRuntime: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2271)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Parcel.writeParcelable(Parcel.java:2584)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.packageinstaller.PackageUtil$AppSnippet.writeToParcel(PackageUtil.java:151)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Parcel.writeParcelable(Parcel.java:2584)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:2485)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Parcel.writeValue(Parcel.java:2362)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Bundle.writeToParcel(Bundle.java:1389)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Parcel.writeBundle(Parcel.java:1367)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.content.Intent.writeToParcel(Intent.java:11807)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Parcel.writeTypedObject(Parcel.java:2203)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2077)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5615)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5573)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:6071)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:6038)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.startInstall(PackageInstallerActivity.java:701)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.lambda$bindUi$0(PackageInstallerActivity.java:479)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity.$r8$lambda$RCIm8wl1VPqdfQgkgmrBIDbuvOQ(PackageInstallerActivity.java:0)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.packageinstaller.PackageInstallerActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.packageinstaller.AlertController$ButtonHandler.handleMessage(AlertController.java:144)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
01-16 09:21:33.533  8077  8077 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
01-16 09:21:33.536  1592  8121 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
01-16 09:21:33.537  1592  4471 W ActivityTaskManager:   Force finishing activity com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity

```

**Comment by Poldi1977** [comment]
I have the same problem with my Pixel 8.

**Comment by Catfriend1** [comment]
I now finally have an Android 14 phone (custom ROM). Let's see if I run in to problems... atm it's all fine when it comes to installing and using the app.

**Comment by Catfriend1** [comment]
I've synced the https://github.com/Catfriend1/syncthing-android/releases/download/v1.27.3.0/com.github.catfriend1.syncthingandroid_github_v1.27.3.0_2b00c7a9.apk APK to my phone, clicked it on "Recent changes" within the app, allowed install and it upgraded fine from the previous 1.27.2.1.

**Comment by glutenmancy** [comment]
I still had this issue on my Pixel 6 Pro with stock rom but was able to update to the newest version on fdroid by pushing via adb. For some reason I was unable to get "APK Explorer & Editor" to work.

`.\adb.exe install -r .\com.github.catfriend1.syncthingandroid_1270201.apk`
