### ISSUE TITLE
IllegalStateException: Fragment already added

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#108]
### Version Information
    App Version: 0.x.y
    Syncthing Version: v0.x.y
    Android Version: Android x.y / Cyanogenmod x / ...

### Android Log
    adb shell / logcat
    or MatLog (search on GitHub) output

java.lang.IllegalStateException: Fragment already added: DeviceListFragment{6c7fa09 #9 id=0x7f0900b0}
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1892)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:534)
	at com.nutomic.syncthingandroid.activities.MainActivity.updateViewPager(MainActivity.java:267)
	at com.nutomic.syncthingandroid.activities.MainActivity.onServiceStateChange(MainActivity.java:108)
	at com.nutomic.syncthingandroid.service.SyncthingService.lambda$onServiceStateChange$10$SyncthingService(SyncthingService.java:599)
	at com.nutomic.syncthingandroid.service.SyncthingService$$Lambda$12.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by Catfriend1** [comment]
This happens very rarely and cannot be reproduced at the moment. See https://issuetracker.google.com/issues/36956111

**Comment by Catfriend1** [comment]
Please see debug build in PR #113 and report back if it solves this issue.

**Comment by Catfriend1** [comment]
New release containg the fix: v0.14.51.11

**Comment by Catfriend1** [comment]
[2018-11-03-11-18-06_sync.zip](https://github.com/Catfriend1/syncthing-android/files/2545235/2018-11-03-11-18-06_sync.zip)
This problem hit me again.
Reproducer (from my memory):
- Open syncthing when run conditions apply (Sync on WiFi)
- Let it stay open on "Folders" tab
- Switch the phone's screen off
- Wait 20 minutes
- Leave WiFi, so "run conditions" do no longer apply
- Wait 2 minutes
- Put the screen on
- "Syncthing has crashed" appears

**Comment by Catfriend1** [comment]
Reproducer updated.

**Comment by Catfriend1** [comment]
I expect this problem to be finally solved after PR "Refactor ConfigXml #135" got completed.

**Comment by Catfriend1** [comment]
And yeah, it's still not solved.
Note for me: https://stackoverflow.com/questions/55376472/android-java-lang-illegalstateexception-fragment-already-added/55380021#55380021

`fragmentManager.executePendingTransactions();`

**Comment by Catfriend1** [comment]
Fresh logcat:
```
Motorola Moto G (5S) Plus (sanders_n), Android 8.1

java.lang.IllegalStateException: 
  at androidx.fragment.app.FragmentManagerImpl.addFragment (FragmentManager.java:1916)
  at androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java:765)
  at androidx.fragment.app.FragmentManagerImpl.executeOps (FragmentManager.java:2625)
  at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2411)
  at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2366)
  at androidx.fragment.app.FragmentManagerImpl.execSingleAction (FragmentManager.java:2243)
  at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java:654)
  at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate (FragmentStatePagerAdapter.java:168)
  at androidx.viewpager.widget.ViewPager.populate (ViewPager.java:1244)
  at androidx.viewpager.widget.ViewPager.populate (ViewPager.java:1092)
  at androidx.viewpager.widget.ViewPager.onMeasure (ViewPager.java:1622)
  at android.view.View.measure (View.java:22089)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6606)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1514)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:806)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:685)
  at android.view.View.measure (View.java:22089)
  at androidx.drawerlayout.widget.DrawerLayout.onMeasure (DrawerLayout.java:1119)
  at android.view.View.measure (View.java:22089)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6606)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
  at androidx.appcompat.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java:143)
  at android.view.View.measure (View.java:22089)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6606)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
  at android.view.View.measure (View.java:22089)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6606)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
  at android.view.View.measure (View.java:22089)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6606)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1514)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:806)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:685)
  at android.view.View.measure (View.java:22089)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6606)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
  at com.android.internal.policy.DecorView.onMeasure (DecorView.java:753)
  at android.view.View.measure (View.java:22089)
  at android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:2450)
  at android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:1532)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1789)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1420)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6835)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:911)
  at android.view.Choreographer.doCallbacks (Choreographer.java:723)
  at android.view.Choreographer.doFrame (Choreographer.java:658)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:897)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6626)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)
```
