### ISSUE TITLE
When I try to select a folder on the device, the application crashes

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#111]
Quote from @Rakleed at ( https://github.com/Catfriend1/syncthing-android/issues/44#issuecomment-432409474 )
> LineageOS 15.1, Android 8.1.0, OnePlus 3.
> 10-23 23:34:04.592 D/AndroidRuntime(20068): Shutting down VM
10-23 23:34:04.595 E/AndroidRuntime(20068): FATAL EXCEPTION: main
10-23 23:34:04.595 E/AndroidRuntime(20068): Process: com.github.catfriend1.syncthingandroid.debug, PID: 20068
10-23 23:34:04.595 E/AndroidRuntime(20068): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.app.Activity.startActivityForResult(Activity.java:4487)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.app.Activity.startActivityForResult(Activity.java:4445)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at com.nutomic.syncthingandroid.activities.FolderActivity.onPathViewClick(FolderActivity.java:260)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at com.nutomic.syncthingandroid.activities.FolderActivity.lambda$onCreate$0$FolderActivity(FolderActivity.java:196)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at com.nutomic.syncthingandroid.activities.FolderActivity$$Lambda$0.onClick(Unknown Source:2)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.view.View.performClick(View.java:6294)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.view.View$PerformClick.run(View.java:24770)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.os.Handler.handleCallback(Handler.java:790)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.os.Looper.loop(Looper.java:164)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at java.lang.reflect.Method.invoke(Native Method)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
10-23 23:34:04.595 E/AndroidRuntime(20068): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-23 23:34:04.601 W/ActivityManager( 1030):   Force finishing activity com.github.catfriend1.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.FolderActivity
10-23 23:34:04.610 I/ActivityManager( 1030): Showing crash dialog for package com.github.catfriend1.syncthingandroid.debug u0

**Comment by Catfriend1** [comment]
@Rakleed Can you please test this build and tell me if it solves your problem?
https://drive.google.com/file/d/1K9JSsrQYkUE3ZAbsOaPMmNF86AKMSftY/view?usp=sharing

**Comment by Catfriend1** [comment]
Does the test build run on your phone so you can select paths again @Rakleed ?

**Comment by Rakleed** [comment]
@Catfriend1 sorry, I almost forgot to answer.

Yes, it works now.

But there are a few questions:
1. Why so many ways? I would leave only / storage / emulated / 0 (or immediately give the user the opportunity to select a folder along this path). And if the application is granted root access, then you can also add the path /.
2. And what does this message appear below? What does it mean?
<details><summary>Screenshot</summary>

![screenshot_20181024-113902_syncthing-fork](https://user-images.githubusercontent.com/19418601/47492229-33579e00-d855-11e8-83b8-a88edfedb6c9.png)

</details>

**Comment by Catfriend1** [comment]
It's an Android limitation. This is the old dialog just being in the code for Android 4.x users. I will not improve it as it's deprecated. All new phones should have the SAF file picker from Android, sorry for the glitch but it's caused by your manufacturer and using the old dialog code as fallback is just a dirty help instead of nothing. For that reason I think it was why the official project didn't care about the issue with no Activity of a file manager taking the intent. I'll make a release with the "fix" soon for you. Thanks for understanding.

**Comment by Catfriend1** [comment]
Rereading this: emulated/0 is not the only path in Android's history where you can find to your sdcard or intsdcard path. If there was a big username still relying on Android 4.x maybe I'd touch the code one day again... Until then, PR's for FolderPickerActivity are also welcome.

**Comment by Catfriend1** [comment]
New release containg the fix: v0.14.51.11

**Comment by Catfriend1** [comment]
@ruudschouten Hi! Sorry I referred you to the wrong issue before, this is the issue and fix for your problem. Would you like to try the latest release and report back if your issue is solved?
https://github.com/Catfriend1/syncthing-android/releases/download/v0.14.51.13/com.github.catfriend1.syncthingandroid_4176_0.14.51.13_8b15993.apk

**Comment by Catfriend1** [comment]
https://github.com/syncthing/syncthing-android/issues/1235#issuecomment-464147023

**Comment by ayush19283** [comment]
> New release containg the fix: v0.14.51.11

can you please provide the code to select directory if SAF is not supported in my device. I am looking for it from many days and could not find anywhere. Plese help @Catfriend1
