### ISSUE TITLE
Stuck in "starting" state after flight mode

### ISSUE THREAD

**Issue by 101101100** [Catfriend1/syncthing-android#1138]
### 2 devices, one with Android 12, the other a different brand WIFI only tablet with Android 14, I usually put in flight mode over night. (via Tasker tasks, see below). In the morning, when I turn off flight mode and energy saving and activate auto-sync, I observe that Syncthing-Fork sporadically (or frequently on my devices) gets stuck with the yellow indicator while starting and does not reach run mode.  
(Instead I expect that Syncthing-Fork starts an then runs, as it does when it is quit and re-opened in this situation and always.)  
Synthing-Fork is configured to run in WLAN (no restrictions on which ones) and stop in power saving mode. (It is not configured to run only with auto-sync on.)  
The issue happens when I am at home, i.e. the devices quickly connect to the WLAN, can't tell what would happen with WLAN absent. While I write this, I notice that the tablet's Tasker task did not even switch power saving, so issue seems to solely depend on flight mode.  
The Tasker sequences are: auto-sync off, power save on, flight mode on in the evening, flight mode off, power mode normal, auto-sync on in the morning.  
  
### Version Information. 
- App Version: v1.27.9.0. 
- Syncthing Version: v1.27.9. 
- Android Version:          a) Android 12.0.0 ;       b) Android 14 One UI 6.1. 
- Device manufacturer:  a) Huawei ;                   b) Samsung. 
- Device model:              a) P40 pro VOG-L29 ;   b) Galaxy Tab S7 FE SM-T733. 
  
### Device platform info. 

Did not perform this, can add it if really useful 🙂. 
  
```sh

```

### Android Log. 

Did not fetch log yet, can do it if I'm asked to 🙂.  

```sh

```

**Comment by Kaiserdragon2** [comment]
I have this issue as well but i don't switch Wlan  of. Only connect to VPN or switch to mobile and there are multiple access points the phone switches between. I am not sure when it gets stuck in the starting phase.

I hope these logs help.

```
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	... 3 more
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:104)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:91)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.setSoTimeout(Socket.java:1203)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.getImpl(Socket.java:577)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.createImpl(Socket.java:517)
1730703856.133 10688 16412 16412 W PollWebGuiAvailableTask: Caused by: java.net.SocketException: socket failed: ENONET (Machine is not on the network)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	... 3 more
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:104)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:91)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.setSoTimeout(Socket.java:1203)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.getImpl(Socket.java:577)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.createImpl(Socket.java:517)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: Caused by: java.net.SocketException: socket failed: ENONET (Machine is not on the network)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:173)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: com.android.volley.NoConnectionError: java.net.SocketException: socket failed: ENONET (Machine is not on the network)
1730703856.286 10688 16412 16412 W PollWebGuiAvailableTask: Unexpected error while polling web gui
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:104)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:91)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.setSoTimeout(Socket.java:1203)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.getImpl(Socket.java:577)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at java.net.Socket.createImpl(Socket.java:517)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: Caused by: java.net.SocketException: socket failed: ENONET (Machine is not on the network)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:173)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: com.android.volley.NoConnectionError: java.net.SocketException: socket failed: ENONET (Machine is not on the network)
1730703856.440 10688 16412 16412 W PollWebGuiAvailableTask: Unexpected error while polling web gui
```

**Comment by Catfriend1** [comment]
Duplicate of the vpn stuck state ticket.
