### ISSUE TITLE
Remote Control Broadcast crashes Syncthing

### ISSUE THREAD

**Issue by charleshan** [Catfriend1/syncthing-android#1187]
### Description of the issue
The Stop Remote Control Broadcast kills the app.

### Reproduction Steps
1. Open Syncthing-Fork
2. Send com.github.catfriend1.syncthingandroid.action.START(works)
3. Send com.github.catfriend1.syncthingandroid.action.STOP(works)
4. Send com.github.catfriend1.syncthingandroid.action.START(doesn't work)

It works again once I manually open Syncthing-Fork.

### Version Information
- App Version: v1.28.0
- Syncthing Version: v1.28.0
- Android Version: Android 15
- Device manufacturer: Google
- Device model: Pixel 7

**Comment by charleshan** [comment]
```
12-02 20:46:52.937  1751  5092 W ActivityManager: Background started FGS: Disallowed [callingPackage: com.github.catfriend1.syncthingandroid; callingUid: 10405; uidState: RCVR; uidBFSL: n/a; intent: Intent { cmp=com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService }; code:DENIED; tempAllowListReason:<null>; targetSdkVersion:35; callerTargetSdkVersion:35; startForegroundCount:0; bindFromPackage:null: isBindService:false]
12-02 20:46:52.937  1751  5092 W ActivityManager: startForegroundService() not allowed due to mAllowStartForeground false: service com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService
12-02 20:46:52.937  1751  5092 D CompatChangeReporter: Compat change id reported: 313677553; UID 10405; state: ENABLED
12-02 20:46:52.940 27475 27475 D AndroidRuntime: Shutting down VM
12-02 20:46:52.942 27475 27475 E AndroidRuntime: FATAL EXCEPTION: main
12-02 20:46:52.942 27475 27475 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 27475
12-02 20:46:52.942 27475 27475 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.nutomic.syncthingandroid.receiver.AppConfigReceiver: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4781)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2436)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Parcel.readParcelableInternal(Parcel.java:5075)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Parcel.readParcelable(Parcel.java:5057)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3237)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3226)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3209)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3151)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6393)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1960)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1935)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at com.nutomic.syncthingandroid.util.Util$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at com.nutomic.syncthingandroid.receiver.BootReceiver.startServiceCompat(BootReceiver.java:69)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at com.nutomic.syncthingandroid.receiver.AppConfigReceiver.onReceive(AppConfigReceiver.java:55)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4772)
12-02 20:46:52.942 27475 27475 E AndroidRuntime: 	... 9 more
12-02 20:46:52.945  1751  4849 W MagnificationConnectionManager: requestConnection duplicated request: connect=false, mConnectionState=DISCONNECTED
12-02 20:46:52.948  1751  1822 I ActivityManager: Showing crash dialog for package com.github.catfriend1.syncthingandroid u0
```

Found a couple of related issues:
- https://github.com/Catfriend1/syncthing-android/issues/1109
- https://github.com/syncthing/syncthing-android/issues/1875

Followed @Catfriend1's advice of reinstalling the app. Reinstalling from F-Droid didn't help. Reinstalling from Google Play fixed the issue.

**Comment by charleshan** [comment]
Actually, this still happens when the intent is sent when the phone's screen is off. It doesn't happen every time but it does happen every few hours.

## Steps to reproduce the issue
1. Create the following recurring tasks that runs every hour using Tasker, Automate, etc:
    - Sends com.github.catfriend1.syncthingandroid.action.START
    - Waits for 1 minute
    - Sends com.github.catfriend1.syncthingandroid.action.STOP
2. Open Syncthing and don't manually open Syncthing for a day

**Comment by Catfriend1** [comment]
Currently, Syncthing-Fork does not start on my Android 15 virtual device. I suspect it's the restrictions to foreground services once again. Does it work correctly on Android 14?

**Comment by Catfriend1** [comment]
Ref. https://github.com/syncthing/syncthing-android/issues/1875#issuecomment-1345473739

Try the solution with the latest github release.

**Comment by charleshan** [comment]
Thanks, I'll try that out!

5 hours in. So far so good!

**Comment by Catfriend1** [comment]
6 hours is the "Google Limit"

**Comment by Catfriend1** [comment]
Yes, gplay version is limited.

Thanks for your answer.
