### ISSUE TITLE
i also have this issue, running grapheneOS (android version 15), syncthing and silent notification seem to persist for 24-36hours but then crash and I get a "syncthing-fork keeps stopping" message.

### ISSUE THREAD

**Issue by Keng5594** [Catfriend1/syncthing-android#1213]
``              i also have this issue, running grapheneOS (android version 15), syncthing and silent notification seem to persist for 24-36hours but then crash and I get a "syncthing-fork keeps stopping" message. 

FYI i have battery management settings disabled for syncthing-fork so it does have permissions to run permanently in the background 

crash message pasted below:
```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241005.015/2024103100:user/release-keys
package: com.github.catfriend1.syncthingandroid:1280000, targetSdk 35
process: com.github.catfriend1.syncthingandroid
processUptime: 418 + 370 ms
installer: com.android.vending

java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@633b6a9 with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5199)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5095)
	at android.os.Parcel.readParcelable(Parcel.java:5077)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3246)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7231)
	at android.app.Service.startForeground(Service.java:879)
	at com.nutomic.syncthingandroid.util.Util$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
	at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:216)
	at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:109)
	at com.nutomic.syncthingandroid.service.SyncthingService.onStartCommand(SyncthingService.java:306)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5181)
	... 11 more
```

_Originally posted by @benjamingray123 in https://github.com/Catfriend1/syncthing-android/issues/1175#issuecomment-2457892041_

**Comment by Catfriend1** [comment]
Android 15 restriction, downgrade to 14 or try to use the signed release from here instead of the gplay release.
