### ISSUE TITLE
 Crash - Can't create handler inside thread Thread[AsyncTask] that has not called Looper.prepare

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#142]
### Description of the issue
Introduced while working on PR #135 "Refactor ConfigXml"

### Android Log
> 2018-12-18 12:06:30.327 14809-15221/com.github.catfriend1.syncthingandroid.debug V/SyncthingService: importConfig: Importing index database
2018-12-18 12:06:30.375 14809-15221/com.github.catfriend1.syncthingandroid.debug V/SyncthingService: importConfig END
2018-12-18 12:06:30.376 14809-15221/com.github.catfriend1.syncthingandroid.debug V/SyncthingService: Starting syncthing
2018-12-18 12:06:30.376 14809-15221/com.github.catfriend1.syncthingandroid.debug V/SyncthingService: onServiceStateChange: from DISABLED to STARTING
2018-12-18 12:06:30.376 14809-15221/com.github.catfriend1.syncthingandroid.debug D/ConfigXml: Parsing config file '/data/user/0/com.github.catfriend1.syncthingandroid.debug/files/config.xml'
2018-12-18 12:06:30.376 14809-14809/com.github.catfriend1.syncthingandroid.debug V/NotificationHandler: Starting foreground service or updating notification
2018-12-18 12:06:30.385 14809-15221/com.github.catfriend1.syncthingandroid.debug I/ConfigXml: Successfully parsed config file
2018-12-18 12:06:30.385 14809-15221/com.github.catfriend1.syncthingandroid.debug I/ConfigXml: Found existing config version 28
2018-12-18 12:06:30.388 14809-15221/com.github.catfriend1.syncthingandroid.debug I/SyncthingService: Web GUI will be available at https://127.0.0.1:8384
2018-12-18 12:06:30.430 14809-15221/com.github.catfriend1.syncthingandroid.debug D/SyncthingRunnable: killSyncthing: Found no running instances of libsyncthing.so
CRASH
2018-12-18 12:06:30.433 14809-15221/com.github.catfriend1.syncthingandroid.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.github.catfriend1.syncthingandroid.debug, PID: 14809
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #2,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:205)
        at android.os.Handler.<init>(Handler.java:118)
        at com.nutomic.syncthingandroid.http.PollWebGuiAvailableTask.<init>(PollWebGuiAvailableTask.java:28)
        at com.nutomic.syncthingandroid.service.SyncthingService.launchStartupTask(SyncthingService.java:488)
        at com.nutomic.syncthingandroid.service.SyncthingService.importConfig(SyncthingService.java:955)
        at com.nutomic.syncthingandroid.activities.SettingsActivity$SettingsFragment$ImportConfigTask.doInBackground(SettingsActivity.java:713)
        at com.nutomic.syncthingandroid.activities.SettingsActivity$SettingsFragment$ImportConfigTask.doInBackground(SettingsActivity.java:696)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by Catfriend1** [comment]
Solved by commit #https://github.com/Catfriend1/syncthing-android/pull/135/commits/73c50172180fdd843e2e5d46634d232ec4ee9506
