### ISSUE TITLE
Shorten logcat excerpts

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#364]
### Description of the issue
Shorten logcat excerpts
/Choreographer
/PacProxySelector
/zygote64
/VideoCapabilities
/StrictMode
/ContentCatcher
/cr_CrashFileManager
/cr_AwContents
/cr_ChildProcessConn
/cr_media

**Comment by Catfriend1** [comment]
```
03-10 14:15:35.305 E/StrictMode(20351): java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
03-10 14:15:35.305 E/StrictMode(20351): 	at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
03-10 14:15:35.305 E/StrictMode(20351): 	at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
03-10 14:15:35.305 E/StrictMode(20351): 	at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
03-10 14:15:35.305 E/StrictMode(20351): 	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
03-10 14:15:35.305 E/StrictMode(20351): 	at libcore.io.IoBridge.socket(IoBridge.java:667)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.net.Socket.createImpl(Socket.java:484)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.net.Socket.getImpl(Socket.java:547)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.net.Socket.getReuseAddress(Socket.java:1504)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.net.Network.bindSocket(Network.java:322)
03-10 14:15:35.305 E/StrictMode(20351): 	at cqq.b(SourceFile:22)
03-10 14:15:35.305 E/StrictMode(20351): 	at org.chromium.net.NetworkChangeNotifierAutoDetect.a(SourceFile:85)
03-10 14:15:35.305 E/StrictMode(20351): 	at azd.a(SourceFile:25)
03-10 14:15:35.305 E/StrictMode(20351): 	at org.chromium.android_webview.AwContentsLifecycleNotifier.onWebViewCreated(SourceFile:7)
03-10 14:15:35.305 E/StrictMode(20351): 	at org.chromium.android_webview.AwContents.nativeInit(Native Method)
03-10 14:15:35.305 E/StrictMode(20351): 	at org.chromium.android_webview.AwContents.<init>(SourceFile:79)
03-10 14:15:35.305 E/StrictMode(20351): 	at vw.run(SourceFile:15)
03-10 14:15:35.305 E/StrictMode(20351): 	at aAP.a(SourceFile:13)
03-10 14:15:35.305 E/StrictMode(20351): 	at aAQ.run(SourceFile:2)
03-10 14:15:35.305 E/StrictMode(20351): 	at org.chromium.base.ThreadUtils.b(SourceFile:30)
03-10 14:15:35.305 E/StrictMode(20351): 	at aAP.a(SourceFile:7)
03-10 14:15:35.305 E/StrictMode(20351): 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.b(SourceFile:6)
03-10 14:15:35.305 E/StrictMode(20351): 	at com.android.webview.chromium.WebViewChromium.init(SourceFile:104)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.webkit.WebView.<init>(WebView.java:658)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.webkit.WebView.<init>(WebView.java:588)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.webkit.WebView.<init>(WebView.java:571)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.webkit.WebView.<init>(WebView.java:558)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.createView(LayoutInflater.java:651)
03-10 14:15:35.305 E/StrictMode(20351): 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
03-10 14:15:35.305 E/StrictMode(20351): 	at com.nutomic.syncthingandroid.activities.WebViewActivity.onCreate(WebViewActivity.java:96)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.Activity.performCreate(Activity.java:7098)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.Activity.performCreate(Activity.java:7089)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2766)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2891)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.os.Looper.loop(Looper.java:164)
03-10 14:15:35.305 E/StrictMode(20351): 	at android.app.ActivityThread.main(ActivityThread.java:6648)
03-10 14:15:35.305 E/StrictMode(20351): 	at java.lang.reflect.Method.invoke(Native Method)
03-10 14:15:35.305 E/StrictMode(20351): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-10 14:15:35.305 E/StrictMode(20351): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
03-10 14:15:35.308 E/StrictMode(20351): null
```

**Comment by Catfriend1** [comment]
Exclude zygote64 due to: https://github.com/Catfriend1/syncthing-android/issues/409
