### ISSUE TITLE
F-Droid build fails

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#388]
```
com.github.catfriend1.syncthingandroid/lastbuild 1010005
build session started at 2019-03-26 05:12:13Z
this build started at 2019-03-26 06:54:17Z
this build completed at 2019-03-26 07:00:57Z
fdroiddata: 5b7f7041ad9571b0f4ffc3fcca30649262a199e2
fdroidserverid: aa47e93f36208364c25a1a2ed7622d6c20dc773d
buildserverid: aa47e93f36208364c25a1a2ed7622d6c20dc773d
Installed Android Tools
Build Log
'Build.py failed on server for com.github.catfriend1.syncthingandroid:1.1.0.5'
detail
[...]
github.com/syncthing/syncthing
   675f289a..d4e81fff  master      -> origin/master
   50d8c43e..e4ab9d33  release     -> origin/release
 * [new tag]           v1.1.1-rc.2 -> v1.1.1-rc.2
Invoking git describe ...
Cleaning go-build cache
go: finding github.com/prometheus/client_golang v0.9.2
go: finding github.com/AudriusButkevicius/go-nat-pmp v0.0.0-20160522074932-452c97607362
go: finding github.com/rcrowley/go-metrics v0.0.0-20171128170426-e181e095bae9
go: finding github.com/oschwald/geoip2-golang v1.1.0
go: finding github.com/thejerf/suture v3.0.2+incompatible
go: finding github.com/bkaradzic/go-lz4 v0.0.0-20160924222819-7224d8d8f27e
go: finding github.com/d4l3k/messagediff v1.2.1
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/kr/pretty v0.1.0
go: finding golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
go: finding github.com/onsi/ginkgo v0.0.0-20171221013426-6c46eb8334b3
go: finding github.com/oschwald/maxminddb-golang v0.0.0-20170901134056-26fe5ace1c70
go: finding github.com/chmduquesne/rollinghash v0.0.0-20180912150627-a60f8e7142b5
go: finding gopkg.in/asn1-ber.v1 v1.0.0-20170511165959-379148ca0225
go: finding github.com/kr/text v0.1.0
go: finding github.com/syndtr/goleveldb v0.0.0-20171214120811-34011bf325bc
go: finding github.com/urfave/cli v1.20.0
go: finding github.com/calmh/du v1.0.1
go: finding gopkg.in/ldap.v2 v2.5.1
go: finding github.com/gogo/protobuf v1.2.0
go: finding github.com/golang/snappy v0.0.0-20170215233205-553a64147049
go: finding github.com/lib/pq v1.0.0
go: finding github.com/golang/groupcache v0.0.0-20171101203131-84a468cf14b4
go: finding github.com/minio/sha256-simd v0.0.0-20190117184323-cc1980cb0338
go: finding golang.org/x/text v0.0.0-20171227012246-e19ae1496984
go: finding gopkg.in/yaml.v2 v2.0.0-20171116090243-287cf08546ab
go: finding golang.org/x/crypto v0.0.0-20171231215028-0fcca4842a8d
go: finding github.com/syncthing/notify v0.0.0-20181107104724-4e389ea6c0d8
go: finding golang.org/x/time v0.0.0-20170927054726-6dc17368e09b
go: finding github.com/sasha-s/go-deadlock v0.2.0
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: finding github.com/AudriusButkevicius/recli v0.0.5
go: finding github.com/vitrun/qart v0.0.0-20160531060029-bf64b92db6b0
go: finding github.com/calmh/xdr v1.1.0
go: finding github.com/mattn/go-isatty v0.0.4
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: finding github.com/kballard/go-shellquote v0.0.0-20170619183022-cd60e84ee657
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/onsi/gomega v0.0.0-20171227184521-ba3724c94e4d
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding github.com/jackpal/gateway v0.0.0-20161225004348-5795ac81146e
go: finding golang.org/x/sys v0.0.0-20180926160741-c2ed4eda69e7
go: finding github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/kr/pty v1.1.1
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding github.com/gobwas/glob v0.0.0-20170212200151-51eb1ee00b6d
go: finding github.com/petermattis/goid v0.0.0-20170816195418-3db12ebb2a59
go: finding golang.org/x/sys v0.0.0-20181213200352-4d1cda033e06
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/pmezard/go-difflib v1.0.0
Building syncthing version v1.1.0
Building for arm
go: finding github.com/petermattis/goid v0.0.0-20170816195418-3db12ebb2a59
go: finding github.com/syndtr/goleveldb v0.0.0-20171214120811-34011bf325bc
go: finding github.com/bkaradzic/go-lz4 v0.0.0-20160924222819-7224d8d8f27e
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/AudriusButkevicius/go-nat-pmp v0.0.0-20160522074932-452c97607362
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/prometheus/client_golang v0.9.2
go: finding github.com/onsi/gomega v0.0.0-20171227184521-ba3724c94e4d
go: finding github.com/thejerf/suture v3.0.2+incompatible
go: finding golang.org/x/crypto v0.0.0-20171231215028-0fcca4842a8d
go: finding golang.org/x/time v0.0.0-20170927054726-6dc17368e09b
go: finding github.com/AudriusButkevicius/recli v0.0.5
go: finding golang.org/x/text v0.0.0-20171227012246-e19ae1496984
go: finding github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: finding github.com/chmduquesne/rollinghash v0.0.0-20180912150627-a60f8e7142b5
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/gogo/protobuf v1.2.0
go: finding github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: finding github.com/gobwas/glob v0.0.0-20170212200151-51eb1ee00b6d
go: finding gopkg.in/ldap.v2 v2.5.1
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding gopkg.in/yaml.v2 v2.0.0-20171116090243-287cf08546ab
go: finding github.com/minio/sha256-simd v0.0.0-20190117184323-cc1980cb0338
go: finding github.com/calmh/du v1.0.1
go: finding github.com/rcrowley/go-metrics v0.0.0-20171128170426-e181e095bae9
go: finding github.com/syncthing/notify v0.0.0-20181107104724-4e389ea6c0d8
go: finding github.com/golang/groupcache v0.0.0-20171101203131-84a468cf14b4
go: finding gopkg.in/asn1-ber.v1 v1.0.0-20170511165959-379148ca0225
go: finding github.com/onsi/ginkgo v0.0.0-20171221013426-6c46eb8334b3
go: finding github.com/oschwald/maxminddb-golang v0.0.0-20170901134056-26fe5ace1c70
go: finding github.com/mattn/go-isatty v0.0.4
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding github.com/urfave/cli v1.20.0
go: finding github.com/oschwald/geoip2-golang v1.1.0
go: finding github.com/jackpal/gateway v0.0.0-20161225004348-5795ac81146e
go: finding github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: finding github.com/d4l3k/messagediff v1.2.1
go: finding github.com/sasha-s/go-deadlock v0.2.0
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/lib/pq v1.0.0
go: finding github.com/golang/snappy v0.0.0-20170215233205-553a64147049
go: finding github.com/calmh/xdr v1.1.0
go: finding github.com/vitrun/qart v0.0.0-20160531060029-bf64b92db6b0
go: finding github.com/kr/pretty v0.1.0
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding golang.org/x/sys v0.0.0-20180926160741-c2ed4eda69e7
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/kballard/go-shellquote v0.0.0-20170619183022-cd60e84ee657
go: finding golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
go: finding golang.org/x/sys v0.0.0-20181213200352-4d1cda033e06
go: finding github.com/kr/text v0.1.0
go: finding github.com/kr/pty v1.1.1
go: downloading github.com/rcrowley/go-metrics v0.0.0-20171128170426-e181e095bae9
go: downloading golang.org/x/crypto v0.0.0-20171231215028-0fcca4842a8d
Fetching https://golang.org/x/crypto?go-get=1
go: downloading github.com/sasha-s/go-deadlock v0.2.0
go: downloading github.com/vitrun/qart v0.0.0-20160531060029-bf64b92db6b0
go: downloading gopkg.in/ldap.v2 v2.5.1
Fetching https://gopkg.in/ldap.v2?go-get=1
go: downloading github.com/chmduquesne/rollinghash v0.0.0-20180912150627-a60f8e7142b5
go: downloading golang.org/x/time v0.0.0-20170927054726-6dc17368e09b
Fetching https://golang.org/x/time?go-get=1
go: downloading github.com/thejerf/suture v3.0.2+incompatible
go: downloading github.com/syndtr/goleveldb v0.0.0-20171214120811-34011bf325bc
go: downloading github.com/gogo/protobuf v1.2.0
go: downloading github.com/bkaradzic/go-lz4 v0.0.0-20160924222819-7224d8d8f27e
go: downloading golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
Fetching https://golang.org/x/net?go-get=1
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/syncthing/notify v0.0.0-20181107104724-4e389ea6c0d8
go: downloading github.com/calmh/xdr v1.1.0
go: downloading github.com/golang/snappy v0.0.0-20170215233205-553a64147049
go: downloading github.com/gobwas/glob v0.0.0-20170212200151-51eb1ee00b6d
go: downloading github.com/kballard/go-shellquote v0.0.0-20170619183022-cd60e84ee657
Parsing meta tags from https://golang.org/x/time?go-get=1 (status code 200)
get "golang.org/x/time": found meta tag get.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at https://golang.org/x/time?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
get "golang.org/x/crypto": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
get "golang.org/x/net": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net?go-get=1
go: downloading github.com/petermattis/goid v0.0.0-20170816195418-3db12ebb2a59
Parsing meta tags from https://gopkg.in/ldap.v2?go-get=1 (status code 200)
get "gopkg.in/ldap.v2": found meta tag get.metaImport{Prefix:"gopkg.in/ldap.v2", VCS:"git", RepoRoot:"https://gopkg.in/ldap.v2"} at https://gopkg.in/ldap.v2?go-get=1
go: downloading github.com/calmh/du v1.0.1
go: downloading github.com/minio/sha256-simd v0.0.0-20190117184323-cc1980cb0338
go: downloading github.com/AudriusButkevicius/go-nat-pmp v0.0.0-20160522074932-452c97607362
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20170511165959-379148ca0225
Fetching https://gopkg.in/asn1-ber.v1?go-get=1
go: downloading github.com/jackpal/gateway v0.0.0-20161225004348-5795ac81146e
go: downloading golang.org/x/sys v0.0.0-20181213200352-4d1cda033e06
Fetching https://golang.org/x/sys?go-get=1
go: downloading golang.org/x/text v0.0.0-20171227012246-e19ae1496984
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://gopkg.in/asn1-ber.v1?go-get=1 (status code 200)
get "gopkg.in/asn1-ber.v1": found meta tag get.metaImport{Prefix:"gopkg.in/asn1-ber.v1", VCS:"git", RepoRoot:"https://gopkg.in/asn1-ber.v1"} at https://gopkg.in/asn1-ber.v1?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text?go-get=1
errors
internal/cpu
internal/race
runtime/internal/sys
internal/bytealg
runtime/internal/atomic
sync/atomic
unicode
runtime
unicode/utf8
math
internal/testlog
math/bits
strconv
crypto/internal/subtle
crypto/subtle
container/list
crypto/rc4
golang_org/x/crypto/cryptobyte/asn1
golang_org/x/net/dns/dnsmessage
internal/nettrace
runtime/cgo
# runtime/cgo
fork/exec /home/vagrant/android-ndk/r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang: no such file or directory
encoding
unicode/utf16
github.com/syncthing/syncthing/lib/auto
golang.org/x/net/internal/iana
github.com/gobwas/glob/util/runes
github.com/vitrun/qart/gf256
image/color
golang.org/x/crypto/blowfish
sync
io
syscall
bytes
bufio
reflect
time
internal/poll
internal/syscall/unix
os
hash
fmt
sort
encoding/binary
hash/crc32
strings
compress/flate
path/filepath
io/ioutil
path
compress/gzip
archive/zip
context
crypto/cipher
crypto/aes
math/rand
crypto
crypto/des
crypto/internal/randutil
crypto/sha512
math/big
crypto/hmac
crypto/md5
crypto/sha1
crypto/sha256
encoding/hex
encoding/base64
encoding/pem
internal/singleflight
net/url
golang_org/x/crypto/internal/chacha20
golang_org/x/crypto/poly1305
golang_org/x/crypto/chacha20poly1305
crypto/rand
crypto/elliptic
encoding/asn1
crypto/rsa
crypto/ecdsa
crypto/dsa
crypto/x509/pkix
golang_org/x/crypto/cryptobyte
golang_org/x/crypto/curve25519
encoding/json
flag
log
runtime/debug
text/tabwriter
runtime/pprof
regexp/syntax
encoding/xml
regexp
github.com/syncthing/syncthing/lib/build
github.com/syncthing/syncthing/lib/logger
github.com/petermattis/goid
os/user
github.com/sasha-s/go-deadlock
github.com/calmh/du
hash/fnv
github.com/syncthing/syncthing/lib/sync
github.com/pkg/errors
github.com/syncthing/syncthing/lib/events
golang.org/x/net/bpf
golang_org/x/text/transform
golang_org/x/text/unicode/bidi
golang_org/x/text/unicode/norm
golang_org/x/text/secure/bidirule
golang_org/x/net/http2/hpack
mime
golang_org/x/net/idna
mime/quotedprintable
net/http/internal
golang.org/x/text/transform
golang.org/x/text/unicode/norm
encoding/base32
github.com/bkaradzic/go-lz4
github.com/gogo/protobuf/proto
github.com/syncthing/syncthing/lib/rand
github.com/minio/sha256-simd
github.com/syncthing/syncthing/lib/sha256
github.com/syncthing/syncthing/lib/upgrade
github.com/syncthing/syncthing/lib/util
github.com/kballard/go-shellquote
os/exec
github.com/thejerf/suture
github.com/calmh/xdr
golang.org/x/time/rate
github.com/syndtr/goleveldb/leveldb/util
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/comparer
github.com/syndtr/goleveldb/leveldb/storage
github.com/syndtr/goleveldb/leveldb/errors
github.com/syndtr/goleveldb/leveldb/filter
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/opt
github.com/golang/snappy
github.com/syndtr/goleveldb/leveldb/table
github.com/syndtr/goleveldb/leveldb
github.com/gogo/protobuf/protoc-gen-gogo/descriptor
github.com/gogo/protobuf/gogoproto
github.com/gobwas/glob/util/strings
github.com/gobwas/glob/match
github.com/syncthing/syncthing/lib/protocol
github.com/gobwas/glob/syntax/lexer
github.com/gobwas/glob/syntax/ast
github.com/gobwas/glob/compiler
github.com/gobwas/glob/syntax
github.com/gobwas/glob
hash/adler32
github.com/chmduquesne/rollinghash
github.com/chmduquesne/rollinghash/adler32
github.com/syncthing/syncthing/lib/weakhash
github.com/vitrun/qart/coding
image
github.com/vitrun/qart/qr
golang.org/x/crypto/bcrypt
gopkg.in/asn1-ber.v1
html
text/template/parse
runtime/trace
os/signal
text/template
html/template
exit status 2
exit status 1
Traceback (most recent call last):
  File "./build-syncthing.py", line 396, in <module>
    ] + ['-no-upgrade', 'build'], env=environ, cwd=syncthing_dir)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/vagrant/build/com.github.catfriend1.syncthingandroid/go/bin/go', 'run', 'build.go', '-goos', 'android', '-goarch', 'arm', '-cc', '/home/vagrant/android-ndk/r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang', '-version', u'v1.1.0', '-no-upgrade', 'build']' returned non-zero exit status 1

> Task :syncthing:buildNative FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':syncthing:buildNative'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 0s
1 actionable task: 1 executed
==== detail end ====
```

**Comment by Catfriend1** [comment]
I think we need to bump up the NDK to 19c ...

**Comment by Catfriend1** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/4664

**Comment by Catfriend1** [comment]
It should be solved, waiting for next build cycle...
