### ISSUE TITLE
Intent resolving bugs

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#504]
Ref.: https://github.com/syncthing/syncthing-android/issues/1382

**Comment by Catfriend1** [comment]
@AssasinRain

adb shell am start -n com.github.catfriend1.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.ShareActivity

```
2019-10-04 22:01:44.812 19435-19435/com.github.catfriend1.syncthingandroid.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.catfriend1.syncthingandroid.debug, PID: 19435
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.catfriend1.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.ShareActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.nutomic.syncthingandroid.activities.ShareActivity.onCreate(ShareActivity.java:137)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
```

**Comment by Catfriend1** [comment]
@AssassinRain Patch incoming ...
![image](https://user-images.githubusercontent.com/16361913/66236637-4e808e00-e6f3-11e9-85d1-b05dea708ae7.png)

**Comment by Catfriend1** [comment]
Need to check this, quote from original ticket:

```
2.com.nutomic.syncthingandroid.activities.ShareActivity
The exception trace is:
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.ShareActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.easter.test.MyParcelable
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.easter.test.MyParcelable
at android.os.Parcel.readParcelableCreator(Parcel.java:2871)
at android.os.Parcel.readParcelable(Parcel.java:2797)
at android.os.Parcel.readValue(Parcel.java:2700)
at android.os.Parcel.readArrayMapInternal(Parcel.java:3067)
at android.os.BaseBundle.unparcel(BaseBundle.java:257)
at android.os.Bundle.getParcelable(Bundle.java:888)
at android.content.Intent.getParcelableExtra(Intent.java:7734)
at com.nutomic.syncthingandroid.activities.ShareActivity.onCreate(ShareActivity.java:123)
at android.app.Activity.performCreate(Activity.java:7183)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
... 9 more

And there are the parameters of our Intent: action: android.intent.action.SEND;; category: null;; data: null;; type: null;; Extra-data: Parcelable->android.intent.extra.STREAM->ParcelableObj
```

**Comment by Catfriend1** [comment]
`adb shell am start -n com.github.catfriend1.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.ShareActivity -a android.intent.action.SEND`

**Comment by Catfriend1** [comment]
@AssassinRain: I'm not sure how to reproduce your finding (2). Can you please tell me which tool you used for that?

**Comment by Catfriend1** [comment]
I've wrapped those "suspicious" getIntentExtra STREAM lines into a try and catch block which prevents the app from crashing out on a malformed intent. That should solve it. Thanks for reporting.

**Comment by AssassinRain** [comment]
Thanks for your kindly reply.
We are a group of researchers focusing on detecting the potential bugs of Android apps.
And the tool was developed by ourselves.

**Comment by Catfriend1** [comment]
Do you have any plans to make the tool public? I'm asking because it would have so much aided in verifying if my code patch really corrected the problem.

**Comment by AssassinRain** [comment]
Thanks for your interest in our tool.
We plan to make the tool public after the corresponding paper is accepted, which is still under peer-reviewing.
