### ISSUE TITLE
android.view.ViewRootImpl$CalledFromWrongThreadException if key generation failed

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#55]
### Description of the issue
Reported by @Avamander in #44.
Quote: @Catfriend1  the app crashes on the key generation screen.

### Reproducer
Run app for the first time. Simulate key generation to fail. App will crash then instead of showing a message.

### Version Information
    App Version: 0.14.51.rc3.2
    Syncthing Version: v0.14.51-rc.3
    Android Version: Android 7.1.2

### Android Log
```Java
E/AndroidRuntime( 9864): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime( 9864): Process: com.github.catfriend1.syncthingandroid.debug, PID: 9864
E/AndroidRuntime( 9864): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 9864):        at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime( 9864):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 9864):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 9864):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 9864):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 9864):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 9864):        at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime( 9864): Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime( 9864):        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6027)
E/AndroidRuntime( 9864):        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:820)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.view.View.requestLayout(View.java:16455)
E/AndroidRuntime( 9864):        at android.widget.TextView.checkForRelayout(TextView.java:6600)
E/AndroidRuntime( 9864):        at android.widget.TextView.setText(TextView.java:3813)
E/AndroidRuntime( 9864):        at android.widget.TextView.setText(TextView.java:3671)
E/AndroidRuntime( 9864):        at android.widget.TextView.setText(TextView.java:3646)
E/AndroidRuntime( 9864):        at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:484)
E/AndroidRuntime( 9864):        at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:465)
E/AndroidRuntime( 9864):        at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime( 9864):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 9864):        ... 3 more
W/ActivityManager(  600):   Force finishing activity com.github.catfriend1.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.FirstStartActivity
```

**Comment by Catfriend1** [comment]
Sidenote - https://stackoverflow.com/questions/7474379/asynctask-only-the-original-thread-that-created-a-view-hierarchy-can-touch-its

**Comment by Catfriend1** [comment]
Thanks @Avamander for reporting this problem! :-)
