### ISSUE TITLE
A race

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#712]
```
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.nutomic.syncthingandroid.model.Gui com.nutomic.syncthingandroid.model.Config.gui' on a null object reference
	at com.nutomic.syncthingandroid.service.RestApi.getWebGuiUrl(RestApi.java:463)
	at com.nutomic.syncthingandroid.service.RestApi.sendConfig(RestApi.java:483)
	at com.nutomic.syncthingandroid.activities.SettingsActivity$SettingsFragment.onStop(SettingsActivity.java:737)
	at android.app.Fragment.performStop(Fragment.java:2241)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:952)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1076)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1058)
	at android.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:1896)
	at android.app.Activity.performStop(Activity.java:6183)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3881)
	... 22 more
```

**Comment by Catfriend1** [comment]
We should not send the config when the screen goes back from settings to main after a config import.
