### ISSUE TITLE
All Files Access & Work Profile Path Bug

### ISSUE THREAD

**Issue by locuturus** [Catfriend1/syncthing-android#733]
Introduction: If you have issues with this fork, feel free to post them. I'll look into them if a good reproducer or log is provided.

### Description of the issue
I'm using All Files Access, because Android 11, and when I create a new folder the file picker appears and I am able to navigate my work profile directories just fine. But once I select the dir I want to use and return to the folder setup I notice that the path is wrong.  

Normal profile uses /storage/emulated/0/* but work profile uses /storage/emulated/10/* so I should see /storage/emulated/10/path/to/my/dir, but the /10/ is changed to a /0/ and so the folder fails to function.

If I use the webgui then I can correctly set up a folder within the /10/ space and have it work.

### Version Information
    App Version: 1.12.0.1
    Syncthing Version: ...
    Android Version: Android 11
    Device manufacturer: Google
    Device model: Pixel 4a

### Device platform info
    adb shell "getprop | grep ro.product"

### Android Log
    adb logcat v
    or MatLog (search on GitHub) output

**Comment by Catfriend1** [comment]
Hi, thanks for reporting it. I expect this to be a bug in the SAF path translation code at FileUtils.java

**Comment by fahrer17** [comment]
Had the same issue today: Couldn't activate permissions to access my data on a Pixel 4a running Android11 (according button was greyed out in the Start menu and I wasn't able to change this no matter what I tried) whereas I had no problems with the original Syncthing app.
Since I really needed to set up my synchronization I didn't have the time to do tests or provide logcats but I find it strange that someone had this problem too on a Pixel 4a (being only a user though).

**Comment by Catfriend1** [comment]
Cause is: https://github.com/Catfriend1/syncthing-android/blob/29b8fc21353329bde672a891ab0b4a88c127850b/app/src/main/java/com/nutomic/syncthingandroid/util/FileUtils.java#L156

`         if (volumeId.equals("primary")) {
                return "/storage/emulated/0";
            }
`

**Comment by Catfriend1** [comment]
Log:
```
2021-03-13 14:16:30.490 2891-2891/com.github.catfriend1.syncthingandroid.debug W/FileUtils: getVolumePath exception
    java.lang.NoSuchMethodException: android.os.storage.StorageVolume.getPath []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.nutomic.syncthingandroid.util.FileUtils.getVolumePath(FileUtils.java:127)
        at com.nutomic.syncthingandroid.util.FileUtils.getAbsolutePathFromTreeUri(FileUtils.java:82)
        at com.nutomic.syncthingandroid.util.FileUtils.getAbsolutePathFromSAFUri(FileUtils.java:61)
        at com.nutomic.syncthingandroid.activities.FolderActivity.onActivityResult(FolderActivity.java:582)
        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-13 14:16:30.491 2891-2891/com.github.catfriend1.syncthingandroid.debug W/FileUtils: getVolumePath failed for volumeId='13EB-2C07'
```

**Comment by Catfriend1** [comment]
So, creating a new user and creating the folder "Test2" in the internal storage root results in the following paths coming up:
```
# find / | grep Test2
/mnt/pass_through/10/emulated/10/Test2
/mnt/pass_through/0/emulated/10/Test2
/mnt/androidwritable/10/emulated/10/Test2
/mnt/installer/10/emulated/10/Test2
/mnt/user/10/emulated/10/Test2
/data/media/10/Test2
```

**Comment by Catfriend1** [comment]
Related: https://stackoverflow.com/questions/31921457/cant-get-path-to-internal-storage

**Comment by Catfriend1** [comment]
OK, this is what you want:
![image](https://user-images.githubusercontent.com/16361913/111031526-4197bc00-8408-11eb-9ce4-86672b78bfa6.png)
