### ISSUE TITLE
Android SDK level 32 (Android 12L) cannot execute SyncthingNative binary

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#898]
Also happens on Android 12 AVD when compiled using SDK level 32.

```
2022-07-06 20:15:43.404 2947-2998/com.github.catfriend1.syncthingandroid.debug E/SyncthingRunnable: Failed to execute syncthing binary or read output
    java.io.IOException: Cannot run program "/data/app/~~inFq19jRdqaHosi1rkH9iw==/com.github.catfriend1.syncthingandroid.debug-auU6sopil0OpoGStydlyXw==/lib/x86_64/libsyncthingnative.so": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at com.nutomic.syncthingandroid.service.SyncthingRunnable.setupAndLaunch(SyncthingRunnable.java:553)
        at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:182)
        at com.nutomic.syncthingandroid.util.ConfigXml.generateConfig(ConfigXml.java:123)
        at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:706)
        at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:688)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at com.nutomic.syncthingandroid.service.SyncthingRunnable.setupAndLaunch(SyncthingRunnable.java:553) 
        at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:182) 
        at com.nutomic.syncthingandroid.util.ConfigXml.generateConfig(ConfigXml.java:123) 
        at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:706) 
        at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:688) 
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2022-07-06 20:15:43.545 2947-2998/com.github.catfriend1.syncthingandroid.debug E/Util: Root is not available. Cannot fix permissions.
2022-07-06 20:15:43.545 2947-2998/com.github.catfriend1.syncthingandroid.debug W/ConfigXml: Failed to open config file '/data/user/0/com.github.catfriend1.syncthingandroid.debug/files/config.xml'
```

**Comment by Catfriend1** [comment]
Seems to be only related to AVD (android virtual devices). It works on a real devices when compiled with SDK version 32.
