### ISSUE TITLE
Crash 1.21.0.2

### ISSUE THREAD

**Issue by Iey4iej3** [Catfriend1/syncthing-android#921]
### Description of the issue

It crashes after update to this version in F-Droid.

### Version Information
- App Version: 1.21.0.2
- Syncthing Version: v1.x.y
- Android Version: Lineage OS 19.1 
- Device manufacturer: 
- Device model: 

### Device platform info

```sh

```

### Android Log

```sh
FATAL EXCEPTION: main
Process: com.github.catfriend1.syncthingandroid, PID: 4194
java.lang.ArrayIndexOutOfBoundsException: length=1; index=2
	at com.nutomic.syncthingandroid.util.Util.readableFileSize(Util.java:72)
	at com.nutomic.syncthingandroid.views.FoldersAdapter.updateFolderStatusView(FoldersAdapter.java:214)
	at com.nutomic.syncthingandroid.views.FoldersAdapter.getView(FoldersAdapter.java:84)
	at android.widget.AbsListView.obtainView(AbsListView.java:2398)
	at android.widget.ListView.makeAndAddView(ListView.java:2067)
	at android.widget.ListView.fillDown(ListView.java:793)
	at android.widget.ListView.fillSpecific(ListView.java:1504)
	at android.widget.ListView.layoutChildren(ListView.java:1802)
	at android.widget.AbsListView.onLayout(AbsListView.java:2195)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3755)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3205)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
```

**Comment by fhunter** [comment]
Can confirm - same behavior after update.

Crash happens when Syncthing daemon is started, after switching to either 'devices' or 'folders' tab in UI.

    App Version: 1.21.0.2
    Syncthing Version: v1.21.0
    Android Version: Lineage OS 16.0
    Device manufacturer: Xiaomi
    Device model: Mi Note 3

**Comment by pvagner** [comment]
A workaround if the app is already setup is to press the back button upon launching the app. Otherwise the folders UI appears and the whole app crashes for me.

**Comment by Wijnand** [comment]
I immediately switch to the status tab to keep it running.

**Comment by licaon-kter** [comment]
ref https://gitlab.com/fdroid/fdroiddata/-/issues/2781

ref: https://github.com/Catfriend1/syncthing-android/issues/919

**Comment by innerspacepilot** [comment]
Also if you are fast enough, you can switch to web interface. It's working :)

**Comment by SergeyDjam** [comment]
Yes. Me too. 
Poco X3 GT, MIUI 13.0.6 Global

f-droid

**Comment by xz-dev** [comment]
I confirm it's fixed in 1.21.0.3.

**Comment by SergeyDjam** [comment]
How soon to expect in f-droid?

**Comment by licaon-kter** [comment]
@SergeyDjam https://github.com/Catfriend1/syncthing-android/issues/919

**Comment by donpolaco** [comment]
The same problem on Xiaomi 12 :/
When can I download fix from google play store?

**Comment by Catfriend1** [comment]
continued here: #923

**Comment by Catfriend1** [comment]
See https://github.com/Catfriend1/syncthing-android/releases/tag/v1.21.0.3
