### ISSUE TITLE
Crash after multiple days of uptime on Android 8

### ISSUE THREAD

**Issue by RunningDroid** [Catfriend1/syncthing-android#954]
### Description of the issue
I have a spare android device that I use as an always online Syncthing instance (and IP cam when needed) and sometimes I'll grab it to do something with it and find that Syncthing has crashed.

### Reproduction Steps
1. tell Syncthing-Android to always run
2. ignore the device for somewhere between 2 days and a week
3. turn on the screen & find that syncthing-android has crashed

### Version Information
- App Version: 1.22.2.2
- Syncthing Version: v1.22.2
- Android Version: Android 8.0.0 
- Device manufacturer: Samsung 
- Device model: SM-G930P 

### Device platform info

```sh
[ro.product.board]: [msm8996]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [heroqltespr]
[ro.product.first_api_level]: [23]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-G930P]
[ro.product.name]: [heroqltespr]
[ro.product_ship]: [true]
```

### Android Log

```sh
12-20 23:32:14.313 26908 26908 E AndroidRuntime: FATAL EXCEPTION: main
12-20 23:32:14.313 26908 26908 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 26908
12-20 23:32:14.313 26908 26908 E AndroidRuntime: java.lang.IllegalStateException: Fragment already added: FolderListFragment{bbc2087} (af6b66b3-5322-4fe6-a3e7-967da02322a1) id=0x7f090187}
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1577)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:270)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:899)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.View.measure(View.java:23297)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2881)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1911)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2166)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-20 23:32:14.313 26908 26908 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
12-20 23:32:14.314 26908 26908 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 23:32:14.314 26908 26908 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
12-20 23:32:14.314 26908 26908 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
`beginning of main` follows this, but the earliest message at the time I ran logcat was from 2 minutes after the crash

**Comment by Catfriend1** [comment]
I've spent hours on finding the root cause of the fragmentpager related crashes and finally gave up a while ago.

**Comment by RunningDroid** [comment]
Thanks for trying anyway
