### ISSUE TITLE
Failed to read configuration after device reboot

### ISSUE THREAD

**Issue by jtagcat** [Catfriend1/syncthing-android#964]
### Reproduction Steps
1. App has worked normally for over a year, besides a minor hitch with an update half a year ago requiring clicking 'Next' on startup wizard.
2. Phone ran out of battery with high power draw (not related to the app) while being plugged in to a slow charger.
3. After boot, the app is no longer able to operate. `Failed to create configuration. Check logcat output`

Not related to https://github.com/Catfriend1/syncthing-android/issues/457, although I did have a sync folder for /storage/emulated/0.

```
22:34:15E/AndroidRuntime FATAL EXCEPTION: main
22:34:15E/AndroidRuntime Process: com.github.catfriend1.syncthingandroid, PID: 6960
22:34:15E/AndroidRuntime android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{749f924 u0 com.github.catfriend1.syncthingandroid/com.nutomic.syncthingandroid.service.SyncthingService}
22:34:15E/AndroidRuntime  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1965)
22:34:15E/AndroidRuntime  at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1936)
22:34:15E/AndroidRuntime  at android.app.ActivityThread.access$2700(ActivityThread.java:256)
22:34:15E/AndroidRuntime  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
22:34:15E/AndroidRuntime  at android.os.Handler.dispatchMessage(Handler.java:106)
22:34:15E/AndroidRuntime  at android.os.Looper.loopOnce(Looper.java:201)
22:34:15E/AndroidRuntime  at android.os.Looper.loop(Looper.java:288)
22:34:15E/AndroidRuntime  at android.app.ActivityThread.main(ActivityThread.java:7870)
22:34:15E/AndroidRuntime  at java.lang.reflect.Method.invoke(Native Method)
22:34:15E/AndroidRuntime  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
22:34:15E/AndroidRuntime  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
22:36:42W/ConfigXml Failed to parse config file '/data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml'
22:36:42W/ConfigXml org.xml.sax.SAXParseException: Unexpected end of document
22:36:42W/ConfigXml  at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
22:36:42W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.parseConfig(ConfigXml.java:192)
22:36:42W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.loadConfig(ConfigXml.java:112)
22:36:42W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity.checkForParseableConfig(FirstStartActivity.java:695)
22:36:42W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity.onCreate(FirstStartActivity.java:119)
22:36:42W/ConfigXml  at android.app.Activity.performCreate(Activity.java:8057)
22:36:42W/ConfigXml  at android.app.Activity.performCreate(Activity.java:8037)
22:36:42W/ConfigXml  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
22:36:42W/ConfigXml  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
22:36:42W/ConfigXml  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
22:36:42W/ConfigXml  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
22:36:42W/ConfigXml  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
22:36:42W/ConfigXml  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
22:36:42W/ConfigXml  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
22:36:42W/ConfigXml  at android.os.Handler.dispatchMessage(Handler.java:106)
22:36:42W/ConfigXml  at android.os.Looper.loopOnce(Looper.java:201)
22:36:42W/ConfigXml  at android.os.Looper.loop(Looper.java:288)
22:36:42W/ConfigXml  at android.app.ActivityThread.main(ActivityThread.java:7870)
22:36:42W/ConfigXml  at java.lang.reflect.Method.invoke(Native Method)
22:36:42W/ConfigXml  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
22:36:42W/ConfigXml  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
22:36:42I/Gralloc4 mapper 4.x is not supported
22:36:42W/Gralloc3 mapper 3.x is not supported
22:36:42W/Gralloc4 allocator 4.x is not supported
22:36:42W/Gralloc3 allocator 3.x is not supported
22:36:42I/Gralloc2 Adding additional valid usage bits: 0x202000
22:37:15W/ConfigXml Failed to parse config file '/data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml'
22:37:15W/ConfigXml org.xml.sax.SAXParseException: Unexpected end of document
22:37:15W/ConfigXml  at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
22:37:15W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.parseConfig(ConfigXml.java:192)
22:37:15W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.loadConfig(ConfigXml.java:112)
22:37:15W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity.checkForParseableConfig(FirstStartActivity.java:695)
22:37:15W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity.onCreate(FirstStartActivity.java:119)
22:37:15W/ConfigXml  at android.app.Activity.performCreate(Activity.java:8057)
22:37:15W/ConfigXml  at android.app.Activity.performCreate(Activity.java:8037)
22:37:15W/ConfigXml  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
22:37:15W/ConfigXml  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
22:37:15W/ConfigXml  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
22:37:15W/ConfigXml  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
22:37:15W/ConfigXml  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
22:37:15W/ConfigXml  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
22:37:15W/ConfigXml  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
22:37:15W/ConfigXml  at android.os.Handler.dispatchMessage(Handler.java:106)
22:37:15W/ConfigXml  at android.os.Looper.loopOnce(Looper.java:201)
22:37:15W/ConfigXml  at android.os.Looper.loop(Looper.java:288)
22:37:15W/ConfigXml  at android.app.ActivityThread.main(ActivityThread.java:7870)
22:37:15W/ConfigXml  at java.lang.reflect.Method.invoke(Native Method)
22:37:15W/ConfigXml  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
22:37:15W/ConfigXml  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
22:37:15I/Gralloc4 mapper 4.x is not supported
22:37:15W/Gralloc3 mapper 3.x is not supported
22:37:15W/Gralloc4 allocator 4.x is not supported
22:37:15W/Gralloc3 allocator 3.x is not supported
22:37:15I/Gralloc2 Adding additional valid usage bits: 0x202000
22:39:03I/ConfigXml (Re)Generating keys and config.
22:39:03 WARNING: Key exists; will not overwrite.
22:39:03 INFO: Device ID: REDACTED
22:39:03 WARNING: Failed to generate config and keys: load config: EOF
22:39:03W/SyncthingRunnable exit reason = exitError. Another Syncthing instance may be already running.
22:39:03W/ConfigXml Failed to parse config file '/data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml'
22:39:03W/ConfigXml org.xml.sax.SAXParseException: Unexpected end of document
22:39:03W/ConfigXml  at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
22:39:03W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.parseConfig(ConfigXml.java:192)
22:39:03W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.generateConfig(ConfigXml.java:124)
22:39:03W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:640)
22:39:03W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:622)
22:39:03W/ConfigXml  at android.os.AsyncTask$3.call(AsyncTask.java:394)
22:39:03W/ConfigXml  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:39:03W/ConfigXml  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
22:39:03W/ConfigXml  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
22:39:03W/ConfigXml  at java.lang.Thread.run(Thread.java:920)
22:39:12I/Util     runShellCommandGetOutput: Exited with code 0
22:39:26I/Util     runShellCommandGetOutput: Exited with code 0
22:40:27I/Util     runShellCommandGetOutput: Exited with code 0
22:40:33W/ConfigXml Failed to parse config file '/data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml'
22:40:33W/ConfigXml org.xml.sax.SAXParseException: Unexpected end of document
22:40:33W/ConfigXml  at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
22:40:33W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.parseConfig(ConfigXml.java:192)
22:40:33W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.loadConfig(ConfigXml.java:112)
22:40:33W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity.checkForParseableConfig(FirstStartActivity.java:695)
22:40:33W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity.onCreate(FirstStartActivity.java:119)
22:40:33W/ConfigXml  at android.app.Activity.performCreate(Activity.java:8057)
22:40:33W/ConfigXml  at android.app.Activity.performCreate(Activity.java:8037)
22:40:33W/ConfigXml  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
22:40:33W/ConfigXml  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
22:40:33W/ConfigXml  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
22:40:33W/ConfigXml  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
22:40:33W/ConfigXml  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
22:40:33W/ConfigXml  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
22:40:33W/ConfigXml  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
22:40:33W/ConfigXml  at android.os.Handler.dispatchMessage(Handler.java:106)
22:40:33W/ConfigXml  at android.os.Looper.loopOnce(Looper.java:201)
22:40:33W/ConfigXml  at android.os.Looper.loop(Looper.java:288)
22:40:33W/ConfigXml  at android.app.ActivityThread.main(ActivityThread.java:7870)
22:40:33W/ConfigXml  at java.lang.reflect.Method.invoke(Native Method)
22:40:33W/ConfigXml  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
22:40:33W/ConfigXml  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
22:40:34I/ConfigXml (Re)Generating keys and config.
22:40:35 WARNING: Key exists; will not overwrite.
22:40:35 INFO: Device ID: REDACTED
22:40:35 WARNING: Failed to generate config and keys: load config: EOF
22:40:35W/SyncthingRunnable exit reason = exitError. Another Syncthing instance may be already running.
22:40:35W/ConfigXml Failed to parse config file '/data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml'
22:40:35W/ConfigXml org.xml.sax.SAXParseException: Unexpected end of document
22:40:35W/ConfigXml  at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
22:40:35W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.parseConfig(ConfigXml.java:192)
22:40:35W/ConfigXml  at com.nutomic.syncthingandroid.util.ConfigXml.generateConfig(ConfigXml.java:124)
22:40:35W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:640)
22:40:35W/ConfigXml  at com.nutomic.syncthingandroid.activities.FirstStartActivity$KeyGenerationTask.doInBackground(FirstStartActivity.java:622)
22:40:35W/ConfigXml  at android.os.AsyncTask$3.call(AsyncTask.java:394)
22:40:35W/ConfigXml  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:40:35W/ConfigXml  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
22:40:35W/ConfigXml  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
22:40:35W/ConfigXml  at java.lang.Thread.run(Thread.java:920)
```

### Version Information
- App Version: v1.23.0.0
- Android Version: LineageOS 19
- Device manufacturer: Oneplus
- Device model: dumpling

Checked with adb: config.xml is an empty file. Might be an upstream issue. Though, `func (w *wrapper) Save() error` uses atomic replaces.

**Comment by jtagcat** [comment]
Can reset by removing empty syncthing config file (keeps key and app config). Don't know how the empty file got there, why there are no backups (syncthing keeps backups of the config), and why empty file brings everything to deathbed (even regenerating).

**Comment by Catfriend1** [comment]
```
22:36:42W/ConfigXml Failed to parse config file '/data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml'
22:36:42W/ConfigXml org.xml.sax.SAXParseException: Unexpected end of document
```

I think you already found the root cause: The config file got corrupted somehow. It seems the parser crashes the app while Syncthing tries to regenerate things. The crashing app brings the (sub)process of SyncthingNative down. I didn't reproduce it, just my thoughts what might be happening here. In this case, if you had backed up your Syncthing config with the in-app function to do so, you can uninstall and reinstall the app, then reimport the config to be good to go again.

**Comment by jtagcat** [comment]
Check if the config file is empty:
```
adb shell cat /data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml
```

Remove it:
```
adb shell rm /data/user/0/com.github.catfriend1.syncthingandroid/files/config.xml
```

This time I lost all data due to the phone powering off at 30% with a sudden temperature drop.

**Comment by Catfriend1** [comment]
Ok, but what to do here... Thanks for the report.
